services:
  mysql:
    image: mysql:8.0
    container_name: travel-mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=travel_db
      - MYSQL_USER=travel_user
      - MYSQL_PASSWORD=travel_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql  # Auto-import your existing backup file
    networks:
      - travel-network

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: travel-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/travel_db
      - SPRING_DATASOURCE_USERNAME=travel_user
      - SPRING_DATASOURCE_PASSWORD=travel_password
    depends_on:
      - mysql
    networks:
      - travel-network

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: travel-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - travel-network

networks:
  travel-network:
    driver: bridge

volumes:
  mysql_data: