// travel-buddy-backend/Jenkinsfile
pipeline {
    agent any
    
    tools {
        maven 'Maven-3.8' // Make sure this matches your Jenkins Maven installation
        jdk 'JDK-17'      // Make sure this matches your Jenkins JDK installation
    }
    
    stages {
        stage('Checkout') {
            steps {
                // Get code from your repository
                checkout scm
            }
        }
        
        stage('Compile') {
            steps {
                dir('travel-buddy-backend') {
                    sh 'mvn clean compile'
                }
            }
        }
        
        stage('Test') {
            steps {
                dir('travel-buddy-backend') {
                    sh 'mvn test'
                }
            }
        }
        
        stage('Package') {
            steps {
                dir('travel-buddy-backend') {
                    sh 'mvn package -DskipTests'
                }
            }
        }
        
        stage('Build Docker Image') {
            steps {
                dir('travel-buddy-backend') {
                    sh 'docker build -t travel-backend:latest .'
                }
            }
        }
        
        stage('Deploy') {
            steps {
                sh 'docker run -d -p 8080:8080 travel-backend:latest'
            }
        }
    }
}